sonar.projectKey=Roman-Molchanov-programming_cpp-laboratory-work
sonar.organization=roman-molchanov-programming
sonar.sources=.
sonar.exclusions=**/*.obj,**/*.exe,Debug/**,Release/**,.vs/**,build/**
sonar.cfamily.build-wrapper-output=bw-output
